<a href="https://colab.research.google.com/github/vishnuiyer23ug-stack/computational-statistics-course-4/blob/main/Class_02_Basics_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Python

In [1]:
print('Welcome to Python') #This is to show that even single quotes can work

Welcome to Python


###Variables and Expressions

In [2]:
a = 5 # Int
var1 = 10.0 # Float
str_var = "Alex" # String

In [3]:
a

5

In [4]:
var1

10.0

In [6]:
str_var

'Alex'

In [10]:
type(a) # Use type to check the datatype

int

In [11]:
type(var1)


float

In [12]:
type(str_var)

str

In [13]:
num1 = 1
num2 = 3
num3 = num1/num2
num3 # This is to show that the answers given out by python are not exactly correct owing to finite memory in the computer. The infinte 3s cannot be shown
# Thus there is finite precision when it comes to floating point numbers

0.3333333333333333

In [17]:
y = var1 + a # Adding an int and a float gives us a float
y

15.0

###Operators

In [26]:
p = num1+num2 # Addition
q = num1-num2 # Subtraction
r = num1*num2 #Multiplication
s = num1/num2 #Division
t = num1//num2 # Division but rounded down to the nearest integer, i.e., integer dividend
u = num1%num2 # Modulo gives us the remainder after division
print(p,q,r,s,t,u)

# Alternate ways to print variables
print("p =",p , "q =", q, "r =", r, "s =",s, "t =", t, "u =", u) # Old fashioned way of combining strings and variables

# Another Alternative
print(f"p = {p}")
print(f"The value of p is {p}") # Using f strings

4 -2 3 0.3333333333333333 0 1
p = 4 q = -2 r = 3 s = 0.3333333333333333 t = 0 u = 1
p = 4
The value of p is 4


###Lists

In [29]:
int_list = [1,2,3,4] # List of integers
float_list = [1.0, 2.5, 3.7, 5.5] # List of floats
str_list = ["a", "b", "c", "d"] # List of strings
mixed_list = [1, 2.4, 'a', p] # Can combine different types in one list. Also recognises previously assigned variables
mixed_list

# We prefer using arrays over lists anyway, so we should try to avoid using lists (especially mixed lists as much as possible)

[1, 2.4, 'a', 4]

In [30]:
sum(int_list) # You can carry out regular operations on lists

10

In [32]:
sum(mixed_list) # Elements have to be of the same type for operations like this to make sense

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [33]:
len(float_list) # Gives us the length of the list

4

In [37]:
int_float_list = int_list + float_list # Adding two lists only appends one list to another
int_float_list

[1, 2, 3, 4, 1.0, 2.5, 3.7, 5.5]

In [39]:
int_str_list = int_list + str_list # Since it is concatenation, even this works
int_str_list

[1, 2, 3, 4, 'a', 'b', 'c', 'd']

### Exercise - Calculating the average score of the class

In [61]:
scores = [65, 78, 30, 85]
average_score = sum(scores)/len(scores)
max_score = max(scores) #  Gives the maximum
min_score = min(scores) # Gives the minimum
print(f"The average score is {sum(scores)/len(scores)}, the maximum score is {max_score}, and the minimum is {min_score}") # You can put expression directly into the print statement as well

The average score is 64.5, the maximum score is 85, and the minimum is 30


### Functions and If Statements

In [67]:
def has_student_passed(scores): # After every condition, we put a :
  """
  This is going to be a multi line comment.
  This function takes the score and returns pass if the score
  is above forty.
  """
  if scores >= 40:
    return "The student has passed" # Executed if if condition evaluated true
    """
    return does not necessarily need to have brackets
    """
  else:
    return("The student has failed") # Executed if if condition evaluated false
Pass = [has_student_passed(i) for i in scores] # Creates a list that displays the condition for each score in our scores
Pass

['The student has passed',
 'The student has passed',
 'The student has failed',
 'The student has passed']

### For loop

In [68]:
for i in scores: # You CANNOT put a bracket after for
  print(f"i = {i}")

i = 65
i = 78
i = 30
i = 85


In [72]:
for i in scores:
  print(f"i = {i}, {has_student_passed(i)}")

i = 65, The student has passed
i = 78, The student has passed
i = 30, The student has failed
i = 85, The student has passed


### Homework -Write a Function to calculate the Grade of the Student and return the Grade

In [75]:
# Use either if and elseif, or look up the match function
def student_grades(scores):
  if scores <= 40:
    return "U"
  elif scores >40 and scores <=50:
    return "E"
  elif scores >50 and scores <=60:
    return "D"
  elif scores >60 and scores <=70:
    return "C"
  elif scores >70 and scores <=80:
    return "B"
  elif scores >80 and scores <=90:
    return "A"
  elif scores >90 and scores <=100:
    return "O"

for i in scores: # Using the function to print the scores
  print(f"score = {i}, {student_grades(i)}")

score = 65, C
score = 78, B
score = 30, U
score = 85, A


### Getting Help

In [76]:
# All you have to do is enclose a function within help
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



### Dictionaries

In [79]:
names = ["Alex", "Nandini", "Trusha", "Mohammed"]
# A dictionary is a data structure that does 1-1 mapping of key-value pairs
score_dictionary = {"Alex":scores[0], "Nandini":scores[1], "Trusha":scores[2], "Mohammed":scores[3]}
score_dictionary

{'Alex': 65, 'Nandini': 78, 'Trusha': 30, 'Mohammed': 85}

In [96]:
score_dictionary.keys() # Gives all the keys from the dictionary

dict_keys(['Alex', 'Nandini', 'Trusha', 'Mohammed'])

In [97]:
score_dictionary.values() # Gives all the values from the dictionary

dict_values([65, 78, 30, 85])

### Homework
- Use the dictionary along with the for loop to print the name and the score of the student
- Try calculating the grade of each student inside the for block

In [95]:
for key, score in score_dictionary.items(): # the .items makes each pair one item in a list
  print(f"Name: {key}, Score = {score}, Grade = {student_grades(score)}")

Name: Alex, Score = 65, Grade = C
Name: Nandini, Score = 78, Grade = B
Name: Trusha, Score = 30, Grade = U
Name: Mohammed, Score = 85, Grade = A


## NUMPY

In [98]:
import numpy as np # Importing the package and giving it a short form


In [99]:
zeros_array = np.zeros(10) # An array of 10 zeros, float is the default datatype
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [101]:
# You can make matrices by changing the shape, and you can change the datatype also
zeros_array_int_2d = np.zeros((5,4), dtype= int)
zeros_array_int_2d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [102]:
ones_arr = np.ones(10) # An array of ones
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [103]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr1
arr2 # Only the last array is printed, so it is better to actually use the print function

array([ 6,  7,  8,  9, 10])

In [106]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(f"The first array is {arr1}, and its type is {type(arr1)}") # We are no longer working with a list, it is now a numpy array
print(f"The second array is {arr2}, and its type is {type(arr2)}")

The first array is [1 2 3 4 5], and its type is <class 'numpy.ndarray'>
The second array is [ 6  7  8  9 10], and its type is <class 'numpy.ndarray'>


### Numpy Array Operations

In [107]:
add_arr = arr1 + arr2
add_arr # We can see that there is element wise addition. Most operations happen element wise

array([ 7,  9, 11, 13, 15])

In [109]:
# All the basic operations work the same way essentially
sub_arr = arr1 - arr2
mult_arr = arr1 * arr2
div_arr = arr1 / arr2
print(sub_arr)
print(mult_arr)
print(div_arr)

[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
